### ISSUE TITLE
这个如何打包成一个第三方库呢？

### ISSUE THREAD

**Issue by hjx503838528** [esengine/egret-fairygui-mvc#1]

**Comment by esengine** [comment]
https://github.com/esengine/egret-fairygui-mvc/tree/master/source/bin 

这里已经有打包好的第三方库 直接下载即可

**Comment by esengine** [comment]
推荐是直接下载源码src复制到工程里用 这样断点的时候比较好查问题 毕竟源码也就一点点东西

https://github.com/esengine/egret-fairygui-mvc/tree/master/source/src
